# Zillow House Value Index
- Andrea Cohen
-03.29.2023

## Data
- Home Value data set for:
- Data Type = "ZHVI All Homes (SFR+Condo/Coop) - Time Series - Smoothed - Seasonally Adjusted"
- Geography = "City"
- Share URL:
    - https://drive.google.com/file/d/1O_g44QAfe3uVF-1heAC0BAeVDoWloVR-/view?usp=sharing
- Direct URL (for Pandas):
    - https://docs.google.com/spreadsheets/d/e/2PACX-1vQN3Ksa9szQuO4G1-msXWAp17KtVHQCBnuEieu_auu1wSiBf3-krHusIx5VBMkihxj-KZLBosDIGEyR/pub?output=csv

### Imports

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticks
import matplotlib.dates as mdates

## Prepare the dataset for time series analysis

### Load in the Zillow Home Value Index dataframe

In [2]:
df = pd.read_csv('https://docs.google.com/spreadsheets/d/e/2PACX-1vQN3Ksa9szQuO4G1-msXWAp17KtVHQCBnuEieu_auu1wSiBf3-krHusIx5VBMkihxj-KZLBosDIGEyR/pub?output=csv')
pd.set_option("display.max_columns", 500)
display(df.head())
display(df.info())

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,2015-10-31,2015-11-30,2015-12-31,2016-01-31,2016-02-29,2016-03-31,2016-04-30,2016-05-31,2016-06-30,2016-07-31,2016-08-31,2016-09-30,2016-10-31,2016-11-30,2016-12-31,2017-01-31,2017-02-28,2017-03-31,2017-04-30,2017-05-31,2017-06-30,2017-07-31,2017-08-31,2017-09-30,2017-10-31,2017-11-30,2017-12-31,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,2018-11-30,2018-12-31,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30,2022-07-31,2022-08-31,2022-09-30
0,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,253690.0,255517.0,257207.0,260310.0,263204.0,266206.0,269324.0,272045.0,274610.0,277439.0,280925.0,284072.0,287118.0,289892.0,293193.0,296389.0,299302.0,302120.0,304740.0,307580.0,309783.0,312162.0,314868.0,318074.0,321528.0,323675.0,323070.0,321943.0,NaN,324148.0,326758.0,330210.0,333453.0,336666.0,338838.0,341000.0,343228.0,346501.0,350643.0,355426.0,360063.0,365359.0,369589.0,373404.0,375975.0,378964.0,382001.0,385034.0,388643.0,392144.0,395659.0,398641.0,402494.0,406543.0,411545.0,415806.0,421448.0,427436.0,434280.0,440351.0,445083.0,449783.0,455706.0,462730.0,469737.0,474641.0,481469.0,488465.0,496490.0,504240.0,510505.0,518321.0,524506.0,531180.0,534690.0,537450.0,541227.0,545399.0,548731.0,551922.0,553075.0,551202.0,545438.0,542420.0,541607.0,542651.0,546786.0,548487.0,551304.0,547678.0,546023.0,544485.0,543781.0,544998.0,545412.0,546253.0,546538.0,546098.0,544562.0,541865.0,537685.0,533810.0,529211.0,525290.0,521347.0,518048.0,514767.0,510309.0,505545.0,500172.0,496410.0,492349.0,488965.0,484887.0,480690.0,476296.0,472997.0,470491.0,470036.0,469131.0,469122.0,469123.0,468107.0,467422.0,467058.0,469041.0,471366.0,472308.0,473539.0,473816.0,473416.0,471332.0,470436.0,470023.0,471841.0,472081.0,472328.0,471006.0,469956.0,469250.0,468573.0,467687.0,466847.0,466572.0,466337.0,466059.0,464701.0,464952.0,464835.0,466213.0,466255.0,466479.0,466788.0,467576.0,469609.0,471301.0,472953.0,473970.0,475341.0,477711.0,480285.0,483392.0,485780.0,488756.0,491880.0,495238.0,498503.0,501066.0,504358.0,508460.0,512767.0,517020.0,519548.0,521827.0,523994.0,526960.0,530259.0,532636.0,535174.0,537597.0,539714.0,541519.0,542949.0,546086.0,549158.0,553907.0,557588.0,561230.0,564172.0,567015.0,570778.0,574357.0,577233.0,579539.0,581544.0,585030.0,588447.0,591804.0,594949.0,598075.0,601320.0,604287.0,607787.0,611658.0,615747.0,618357.0,621066.0,623072.0,626662.0,630102.0,634813.0,638447.0,642131.0,646474.0,650521.0,654063.0,656700.0,661012.0,665672.0,669989.0,673514.0,676434.0,678984.0,681140.0,683546.0,685588.0,688553.0,691226.0,693208.0,694425.0,695720.0,695824.0,696173.0,695186.0,695010.0,692926.0,690189.0,687693.0,686304.0,686650.0,688073.0,689697.0,690055.0,690520.0,689921.0,690785.0,691384.0,693097.0,694261.0,696260.0,698929.0,701899.0,703956.0,705003.0,706066.0,707633.0,710706.0,714507.0,719155.0,724138.0,730055.0,735069.0,738773.0,741586.0,745686.0,750578.0,756734.0,762321.0,768797.0,773944.0,777692.0,779960.0,781622.0
1,12447,1,Los Angeles,city,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,234181.0,234401.0,235513.0,237589.0,240113.0,242421.0,244805.0,247479.0,249984.0,252045.0,254055.0,256060.0,257551.0,258958.0,260741.0,263334.0,265878.0,268376.0,270985.0,273798.0,276327.0,279005.0,281443.0,284098.0,286110.0,288395.0,291243.0,295002.0,299197.0,303318.0,308608.0,314186.0,320163.0,325457.0,330810.0,335948.0,340081.0,343717.0,348082.0,352579.0,358310.0,362722.0,369321.0,376132.0,383873.0,389616.0,395321.0,401405.0,408735.0,416092.0,423699.0,433262.0,445159.0,456763.0,467021.0,476362.0,487563.0,498293.0,505613.0,511820.0,516587.0,524782.0,532368.0,540901.0,547877.0,556479.0,566094.0,576654.0,587042.0,598793.0,607044.0,614231.0,620508.0,626117.0,632291.0,636337.0,642588.0,647248.0,650208.0,651968.0,649814.0,649265.0,649062.0,651254.0,652081.0,651964.0,650431.0,649986.0,647314.0,644559.0,639188.0,633784.0,627838.0,620606.0,614172.0,607386.0,603029.0,596635.0,586065.0,571226.0,554589.0,539622.0,524220.0,510520.0,500124.0,490979.0,481905.0,469294.0,460769.0,455196.0,452616.0,449058.0,445538.0,440212.0,436155.0,433816.0,433361.0,433521.0,435313.0,439990.0,441891.0,441100.0,441906.0,444149.0,448457.0,446562.0,444166.0,438616.0,433797.0,428969.0,424735.0,423727.0,423030.0,423778.0,422018.0,420755.0,415887.0,415185.0,413684.0,410970.0,405799.0,400845.0,400207.0,400053.0,399992.0,399912.0,399655.0,400470.0,401682.0,404044.0,406757.0,408448.0,410228.0,414047.0,418700.0,426175.0,432089.0,441439.0,450540.0,461344.0,470086.0,479210.0,488076.0,498065.0,505895.0,511593.0,516896.0,520983.0,526819.0,529072.0,531557.0,531120.0,532665.0,533538.0,535226.0,533443.0,532300.0,532687.0,536244.0,540465.0,545885.0,551341.0,555871.0,556693.0,559510.0,562322.0,562325.0,562658.0,563602.0,569469.0,574208.0,580990.0,585442.0,590203.0,592557.0,598054.0,602206.0,607202.0,606501.0,607920.0,610652.0,617723.0,622027.0,625054.0,629451.0,633173.0,636272.0,637960.0,641862.0,646151.0,647431.0,649442.0,652048.0,658140.0,665500.0,671657.0,677868.0,684769.0,691712.0,697356.0,699877.0,702845.0,703056.0,704432.0,705953.0,710613.0,713509.0,713466.0,713039.0,710740.0,708695.0,708253.0,709540.0,712032.0,709602.0,709570.0,710903.0,716898.0,720486.0,724788.0,728863.0,736897.0,744920.0,751352.0,748812.0,745549.0,749101.0,760154.0,774031.0,785197.0,792777.0,797263.0,800393.0,808089.0,816495.0,829120.0,845605.0,865687.0,888002.0,901552.0,911248.0,914090.0,918444.0,924019.0,928991.0,937936.0,953874.0,973168.0,990391.0,992337.0,992630.0,978196.0,966595.0
2,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,109068.0,109079.0,108878.0,108881.0,108834.0,109066.0,109287.0,109631.0,110062.0,110310.0,110922.0,111504.0,111818.0,111831.0,111368.0,111219.0,111200.0,111416.0,111596.0,111496.0,111641.0,111883.0,112188.0,112411.0,112601.0,112872.0,113392.0,114022.0,114605.0,115065.0,115553.0,116128.0,116623.0,116917.0,117188.0,117382.0,117755.0,117989.0,118364.0,118558.0,118771.0,118916.0,119088.0,119331.0,119438.0,119603.0,119718.0,119995.0,120451.0,121546.0,NaN,124729.0,126049.0,126189.0,127067.0,127414.0,128196.0,128738.0,129328.0,130088.0,130793.0,131511.0,131971.0,132346.0,132419.0,132547.0,132524.0,132422.0,132254.0,132014.0,132173.0,132177.0,132321.0,132127.0,132225.0,132380.0,133032.0,133505.0,134051.0,134400.0,134967.0,135613.0,136102.0,136590.0,136725.0,136530.0,136151.0,136275.0,136707.0,137337.0,137575.0,137931.0,138179.0,138449.0,138636.0,138802.0,138208.0,137512.0,136795.0,136628.0,136228.0,135773.0,135392.0,134770.0,133932.0,133189.0,132247.0,131283.0,130248.0,130095.0,130039.0,130219.0,130392.0,130841.0,131352.0,131430.0,131181.0,130637.0,130546.0,130637.0,130455.0,130296.0,130454.0,130980.0,131366.0,131147.0,130241.0,128782.0,127639.0,126804.0,126407.0,125966.0,125407.0,124819.0,123890.0,123274.0,122771.0,122518.0,122424.0,122361.0,122168.0,121892.0,120903.0,120238.0,119943.0,120246.0,120729.0,120911.0,121210.0,121439.0,121991.0,122476.0,122770.0,122727.0,122968.0,123263.0,124014.0,124929.0,126562.0,128345.0,129986.0,131151.0,132362.0,133688.0,135033.0,136372.0,137593.0,138718.0,139964.0,141302.0,142381.0,143308.0,144178.0,145532.0,146850.0,148466.0,149946.0,151284.0,152468.0,153724.0,155200.0,156514.0,158115.0,159402.0,160644.0,161503.0,161971.0,162318.0,162550.0,163245.0,163767.0,164394.0,165478.0,166518.0,167212.0,167279.0,167752.0,168470.0,169335.0,169585.0,169807.0,170003.0,171100.0,172293.0,172942.0,173418.0,173936.0,174803.0,175355.0,175858.0,175998.0,176105.0,176291.0,176816.0,177493.0,178086.0,178763.0,179315.0,179901.0,180859.0,181862.0,182827.0,183544.0,184466.0,185430.0,186435.0,187384.0,188259.0,189335.0,190241.0,190741.0,190822.0,190969.0,191497.0,192025.0,192652.0,192972.0,193837.0,194401.0,194958.0,194696.0,194963.0,195870.0,197216.0,198080.0,198481.0,198890.0,199804.0,201875.0,204140.0,206623.0,208724.0,210777.0,213157.0,214351.0,216036.0,218153.0,222672.0,227604.0,232956.0,237056.0,240590.0,243006.0,245783.0,248718.0,252080.0,256435.0,261101.0,265558.0,268901.0,271059.0,272400.0,272639.0
3,17426,3,Chicago,city,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,166139.0,166536.0,167368.0,168826.0,170499.0,172008.0,173598.0,175282.0,176928.0,178634.0,180479.0,182259.0,183890.0,185143.0,186789.0,188315.0,190058.0,191482.0,192933.0,194629.0,196416.0,198340.0,199864.0,201093.0,202395.0,203787.0,205605.0,206834.0,208166.0,209016.0,210483.0,212197.0,214267.0,216097.0,217313.0,218765.0,220251.0,222107.0,223677.0,225389.0,226589.0,227809.0,228865.0,230510.0,232266.0,234303.0,236039.0,237862.0,239890.0,241705.0,243394.0,245263.0,247620.0,250097.0,252322.0,254471.0,256412.0,258534.0,260845.0,263400.0,265804.0,268095.0,270328.0,272724.0,275375.0,277971.0,280398.0,282666.0,285374.0,287769.0,290269.0,292733.0,295356.0,297863.0,300221.0,302191.0,303829.0,NaN,305267.0,305664.0,306024.0,305927.0,306047.0,306517.0,307639.0,308738.0,309375.0,309240.0,308595.0,307925.0,306992.0,306281.0,304921.0,303890.0,302715.0,301135.0,300207.0,296063.0,NaN,NaN,293467.0,288495.0,288174.0,283199.0,280695.0,274849.0,271059.0,265306.0,259446.0,255220.0,250583.0,249347.0,246137.0,245064.0,242981.0,241506.0,237514.0,234232.0,230695.0,230395.0,228459.0,228326.0,225504.0,226877.0,225475.0,226811.0,222738.0,220886.0,217038.0,214801.0,211361.0,208225.0,205757.0,203224.0,202110.0,200172.0,199784.0,197983.0,197852.0,196499.0,195393.0,191961.0,190113.0,186620.0,185295.0,181930.0,182673.0,182682.0,183711.0,182998.0,181436.0,180338.0,179230.0,180019.0,180935.0,181766.0,183312.0,184733.0,185970.0,187407.0,189065.0,192164.0,194963.0,197859.0,199540.0,202383.0,203215.0,204818.0,205051.0,207056.0,208148.0,208701.0,209819.0,211624.0,213030.0,213291.0,214040.0,214748.0,215524.0,216288.0,216728.0,217601.0,218417.0,220384.0,221807.0,222303.0,222749.0,223078.0,223321.0,223153.0,223333.0,224649.0,226226.0,229211.0,231164.0,232605.0,232757.0,232923.0,233628.0,234227.0,234846.0,235690.0,237345.0,239254.0,241516.0,243706.0,246315.0,247918.0,248736.0,248387.0,248272.0,248462.0,249600.0,250080.0,250728.0,252046.0,254397.0,256564.0,256995.0,257112.0,257174.0,257461.0,257467.0,257258.0,257917.0,258549.0,259637.0,260447.0,260559.0,261069.0,261214.0,261813.0,261519.0,261110.0,260676.0,260236.0,259915.0,259593.0,259510.0,259625.0,260161.0,261128.0,261799.0,262116.0,262013.0,262362.0,264051.0,266204.0,270202.0,273716.0,276541.0,278154.0,278668.0,280878.0,282423.0,285237.0,286248.0,288347.0,290773.0,293804.0,295841.0,297856.0,300413.0,302821.0,305104.0,306404.0,308303.0,309649.0,312487.0,314663.0,315910.0,315587.0,315429.0
4,6915,4,San Antonio,city,TX,TX,"San Antonio-New Braunfels, TX",Bexar County,114794.0,114975.0,115082.0,115283.0,114407.0,113514.0,112592.0,112695.0,112750.0,112790.0,112738.0,112692.0,112607.0,112447.0,112260.0,112070.0,111959.0,111881.0,111825.0,111817.0,111714.0,111640.0,111471.0,111377.0,111334.0,111466.0,111757.0,112204.0,112587.0,112946.0,113219.0,113618.0,114006.0,114394.0,114881.0,115223.0,115428.0,115391.0,115386.0,115540.0,115857.0,116271.0,116681.0,117088.0,117472.0,117695.0,117641.0,117768.0,118776.0,NaN,122151.0,123627.0,124448.0,125538.0,126241.0,126766.0,127750.0,128357.0,129289.0,129622.0,130060.0,130566.0,131137.0,131750.0,132180.0,132474.0,132584.0,132699.0,132975.0,133588.0,133988.0,134393.0,134621.0,135152.0,135645.0,136189.0,136831.0,137696.0,138721.0,139651.0,140720.0,141767.0,142988.0,144250.0,145130.0,145413.0,145372.0,145589.0,146656.0,147882.0,149158.0,150012.0,150689.0,151343.0,151877.0,152452.0,152126.0,151726.0,151299.0,151489.0,151609.0,151424.0,151045.0,150105.0,149206.0,148389.0,148090.0,147676.0,147095.0,146349.0,145934.0,145661.0,145449.0,144929.0,144355.0,143445.0,142886.0,142567.0,142787.0,142850.0,142957.0,143027.0,143326.0,143584.0,143876.0,143777.0,143659.0,143618.0,143421.0,142792.0,141664.0,140732.0,140113.0,139551.0,139423.0,139001.0,138621.0,137688.0,137167.0,136766.0,136649.0,136413.0,136385.0,135972.0,135756.0,135810.0,136566.0,137348.0,138043.0,138536.0,138661.0,138560.0,138077.0,137993.0,138312.0,138951.0,139899.0,140647.0,141170.0,141377.0,141570.0,142239.0,143034.0,144067.0,145031.0,145911.0,146437.0,146924.0,147594.0,148644.0,149554.0,150348.0,151255.0,152069.0,152742.0,152849.0,153093.0,153572.0,154525.0,155644.0,156562.0,157931.0,159002.0,160170.0,160598.0,161514.0,162516.0,164008.0,164922.0,165843.0,166272.0,167283.0,168463.0,169227.0,170074.0,171239.0,172796.0,173967.0,174358.0,174664.0,174991.0,175326.0,176146.0,177483.0,179664.0,181708.0,182963.0,183369.0,183538.0,184136.0,185027.0,186229.0,187182.0,188290.0,189271.0,189835.0,189921.0,190048.0,191171.0,192393.0,193654.0,194541.0,195509.0,196474.0,196852.0,197563.0,197950.0,199437.0,200654.0,202388.0,203101.0,203903.0,204383.0,205057.0,205714.0,206412.0,207519.0,208253.0,208963.0,208889.0,209397.0,209565.0,210506.0,210427.0,210474.0,210299.0,211203.0,212584.0,214815.0,217354.0,219618.0,221503.0,223364.0,225878.0,228430.0,231954.0,236271.0,242171.0,247519.0,253169.0,256954.0,261034.0,264666.0,269323.0,274032.0,278464.0,284127.0,289739.0,294776.0,297727.0,298796.0,299124.0,298951.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22467 entries, 0 to 22466
Columns: 281 entries, RegionID to 2022-09-30
dtypes: float64(273), int64(2), object(6)
memory usage: 48.2+ MB

None

### Filter the 4 largest cities into a new dataframe

In [3]:
df_largest = df.head(4)
df_largest

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,2000-01-31,2000-02-29,2000-03-31,2000-04-30,2000-05-31,2000-06-30,2000-07-31,2000-08-31,2000-09-30,2000-10-31,2000-11-30,2000-12-31,2001-01-31,2001-02-28,2001-03-31,2001-04-30,2001-05-31,2001-06-30,2001-07-31,2001-08-31,2001-09-30,2001-10-31,2001-11-30,2001-12-31,2002-01-31,2002-02-28,2002-03-31,2002-04-30,2002-05-31,2002-06-30,2002-07-31,2002-08-31,2002-09-30,2002-10-31,2002-11-30,2002-12-31,2003-01-31,2003-02-28,2003-03-31,2003-04-30,2003-05-31,2003-06-30,2003-07-31,2003-08-31,2003-09-30,2003-10-31,2003-11-30,2003-12-31,2004-01-31,2004-02-29,2004-03-31,2004-04-30,2004-05-31,2004-06-30,2004-07-31,2004-08-31,2004-09-30,2004-10-31,2004-11-30,2004-12-31,2005-01-31,2005-02-28,2005-03-31,2005-04-30,2005-05-31,2005-06-30,2005-07-31,2005-08-31,2005-09-30,2005-10-31,2005-11-30,2005-12-31,2006-01-31,2006-02-28,2006-03-31,2006-04-30,2006-05-31,2006-06-30,2006-07-31,2006-08-31,2006-09-30,2006-10-31,2006-11-30,2006-12-31,2007-01-31,2007-02-28,2007-03-31,2007-04-30,2007-05-31,2007-06-30,2007-07-31,2007-08-31,2007-09-30,2007-10-31,2007-11-30,2007-12-31,2008-01-31,2008-02-29,2008-03-31,2008-04-30,2008-05-31,2008-06-30,2008-07-31,2008-08-31,2008-09-30,2008-10-31,2008-11-30,2008-12-31,2009-01-31,2009-02-28,2009-03-31,2009-04-30,2009-05-31,2009-06-30,2009-07-31,2009-08-31,2009-09-30,2009-10-31,2009-11-30,2009-12-31,2010-01-31,2010-02-28,2010-03-31,2010-04-30,2010-05-31,2010-06-30,2010-07-31,2010-08-31,2010-09-30,2010-10-31,2010-11-30,2010-12-31,2011-01-31,2011-02-28,2011-03-31,2011-04-30,2011-05-31,2011-06-30,2011-07-31,2011-08-31,2011-09-30,2011-10-31,2011-11-30,2011-12-31,2012-01-31,2012-02-29,2012-03-31,2012-04-30,2012-05-31,2012-06-30,2012-07-31,2012-08-31,2012-09-30,2012-10-31,2012-11-30,2012-12-31,2013-01-31,2013-02-28,2013-03-31,2013-04-30,2013-05-31,2013-06-30,2013-07-31,2013-08-31,2013-09-30,2013-10-31,2013-11-30,2013-12-31,2014-01-31,2014-02-28,2014-03-31,2014-04-30,2014-05-31,2014-06-30,2014-07-31,2014-08-31,2014-09-30,2014-10-31,2014-11-30,2014-12-31,2015-01-31,2015-02-28,2015-03-31,2015-04-30,2015-05-31,2015-06-30,2015-07-31,2015-08-31,2015-09-30,2015-10-31,2015-11-30,2015-12-31,2016-01-31,2016-02-29,2016-03-31,2016-04-30,2016-05-31,2016-06-30,2016-07-31,2016-08-31,2016-09-30,2016-10-31,2016-11-30,2016-12-31,2017-01-31,2017-02-28,2017-03-31,2017-04-30,2017-05-31,2017-06-30,2017-07-31,2017-08-31,2017-09-30,2017-10-31,2017-11-30,2017-12-31,2018-01-31,2018-02-28,2018-03-31,2018-04-30,2018-05-31,2018-06-30,2018-07-31,2018-08-31,2018-09-30,2018-10-31,2018-11-30,2018-12-31,2019-01-31,2019-02-28,2019-03-31,2019-04-30,2019-05-31,2019-06-30,2019-07-31,2019-08-31,2019-09-30,2019-10-31,2019-11-30,2019-12-31,2020-01-31,2020-02-29,2020-03-31,2020-04-30,2020-05-31,2020-06-30,2020-07-31,2020-08-31,2020-09-30,2020-10-31,2020-11-30,2020-12-31,2021-01-31,2021-02-28,2021-03-31,2021-04-30,2021-05-31,2021-06-30,2021-07-31,2021-08-31,2021-09-30,2021-10-31,2021-11-30,2021-12-31,2022-01-31,2022-02-28,2022-03-31,2022-04-30,2022-05-31,2022-06-30,2022-07-31,2022-08-31,2022-09-30
0,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,253690.0,255517.0,257207.0,260310.0,263204.0,266206.0,269324.0,272045.0,274610.0,277439.0,280925.0,284072.0,287118.0,289892.0,293193.0,296389.0,299302.0,302120.0,304740.0,307580.0,309783.0,312162.0,314868.0,318074.0,321528.0,323675.0,323070.0,321943.0,NaN,324148.0,326758.0,330210.0,333453.0,336666.0,338838.0,341000.0,343228.0,346501.0,350643.0,355426.0,360063.0,365359.0,369589.0,373404.0,375975.0,378964.0,382001.0,385034.0,388643.0,392144.0,395659.0,398641.0,402494.0,406543.0,411545.0,415806.0,421448.0,427436.0,434280.0,440351.0,445083.0,449783.0,455706.0,462730.0,469737.0,474641.0,481469.0,488465.0,496490.0,504240.0,510505.0,518321.0,524506.0,531180.0,534690.0,537450.0,541227.0,545399.0,548731.0,551922.0,553075.0,551202.0,545438.0,542420.0,541607.0,542651.0,546786.0,548487.0,551304.0,547678.0,546023.0,544485.0,543781.0,544998.0,545412.0,546253.0,546538.0,546098.0,544562.0,541865.0,537685.0,533810.0,529211.0,525290.0,521347.0,518048.0,514767.0,510309.0,505545.0,500172.0,496410.0,492349.0,488965.0,484887.0,480690.0,476296.0,472997.0,470491.0,470036.0,469131.0,469122.0,469123.0,468107.0,467422.0,467058.0,469041.0,471366.0,472308.0,473539.0,473816.0,473416.0,471332.0,470436.0,470023.0,471841.0,472081.0,472328.0,471006.0,469956.0,469250.0,468573.0,467687.0,466847.0,466572.0,466337.0,466059.0,464701.0,464952.0,464835.0,466213.0,466255.0,466479.0,466788.0,467576.0,469609.0,471301.0,472953.0,473970.0,475341.0,477711.0,480285.0,483392.0,485780.0,488756.0,491880.0,495238.0,498503.0,501066.0,504358.0,508460.0,512767.0,517020.0,519548.0,521827.0,523994.0,526960.0,530259.0,532636.0,535174.0,537597.0,539714.0,541519.0,542949.0,546086.0,549158.0,553907.0,557588.0,561230.0,564172.0,567015.0,570778.0,574357.0,577233.0,579539.0,581544.0,585030.0,588447.0,591804.0,594949.0,598075.0,601320.0,604287.0,607787.0,611658.0,615747.0,618357.0,621066.0,623072.0,626662.0,630102.0,634813.0,638447.0,642131.0,646474.0,650521.0,654063.0,656700.0,661012.0,665672.0,669989.0,673514.0,676434.0,678984.0,681140.0,683546.0,685588.0,688553.0,691226.0,693208.0,694425.0,695720.0,695824.0,696173.0,695186.0,695010.0,692926.0,690189.0,687693.0,686304.0,686650.0,688073.0,689697.0,690055.0,690520.0,689921.0,690785.0,691384.0,693097.0,694261.0,696260.0,698929.0,701899.0,703956.0,705003.0,706066.0,707633.0,710706.0,714507.0,719155.0,724138.0,730055.0,735069.0,738773.0,741586.0,745686.0,750578.0,756734.0,762321.0,768797.0,773944.0,777692.0,779960.0,781622.0
1,12447,1,Los Angeles,city,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,234181.0,234401.0,235513.0,237589.0,240113.0,242421.0,244805.0,247479.0,249984.0,252045.0,254055.0,256060.0,257551.0,258958.0,260741.0,263334.0,265878.0,268376.0,270985.0,273798.0,276327.0,279005.0,281443.0,284098.0,286110.0,288395.0,291243.0,295002.0,299197.0,303318.0,308608.0,314186.0,320163.0,325457.0,330810.0,335948.0,340081.0,343717.0,348082.0,352579.0,358310.0,362722.0,369321.0,376132.0,383873.0,389616.0,395321.0,401405.0,408735.0,416092.0,423699.0,433262.0,445159.0,456763.0,467021.0,476362.0,487563.0,498293.0,505613.0,511820.0,516587.0,524782.0,532368.0,540901.0,547877.0,556479.0,566094.0,576654.0,587042.0,598793.0,607044.0,614231.0,620508.0,626117.0,632291.0,636337.0,642588.0,647248.0,650208.0,651968.0,649814.0,649265.0,649062.0,651254.0,652081.0,651964.0,650431.0,649986.0,647314.0,644559.0,639188.0,633784.0,627838.0,620606.0,614172.0,607386.0,603029.0,596635.0,586065.0,571226.0,554589.0,539622.0,524220.0,510520.0,500124.0,490979.0,481905.0,469294.0,460769.0,455196.0,452616.0,449058.0,445538.0,440212.0,436155.0,433816.0,433361.0,433521.0,435313.0,439990.0,441891.0,441100.0,441906.0,444149.0,448457.0,446562.0,444166.0,438616.0,433797.0,428969.0,424735.0,423727.0,423030.0,423778.0,422018.0,420755.0,415887.0,415185.0,413684.0,410970.0,405799.0,400845.0,400207.0,400053.0,399992.0,399912.0,399655.0,400470.0,401682.0,404044.0,406757.0,408448.0,410228.0,414047.0,418700.0,426175.0,432089.0,441439.0,450540.0,461344.0,470086.0,479210.0,488076.0,498065.0,505895.0,511593.0,516896.0,520983.0,526819.0,529072.0,531557.0,531120.0,532665.0,533538.0,535226.0,533443.0,532300.0,532687.0,536244.0,540465.0,545885.0,551341.0,555871.0,556693.0,559510.0,562322.0,562325.0,562658.0,563602.0,569469.0,574208.0,580990.0,585442.0,590203.0,592557.0,598054.0,602206.0,607202.0,606501.0,607920.0,610652.0,617723.0,622027.0,625054.0,629451.0,633173.0,636272.0,637960.0,641862.0,646151.0,647431.0,649442.0,652048.0,658140.0,665500.0,671657.0,677868.0,684769.0,691712.0,697356.0,699877.0,702845.0,703056.0,704432.0,705953.0,710613.0,713509.0,713466.0,713039.0,710740.0,708695.0,708253.0,709540.0,712032.0,709602.0,709570.0,710903.0,716898.0,720486.0,724788.0,728863.0,736897.0,744920.0,751352.0,748812.0,745549.0,749101.0,760154.0,774031.0,785197.0,792777.0,797263.0,800393.0,808089.0,816495.0,829120.0,845605.0,865687.0,888002.0,901552.0,911248.0,914090.0,918444.0,924019.0,928991.0,937936.0,953874.0,973168.0,990391.0,992337.0,992630.0,978196.0,966595.0
2,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,109068.0,109079.0,108878.0,108881.0,108834.0,109066.0,109287.0,109631.0,110062.0,110310.0,110922.0,111504.0,111818.0,111831.0,111368.0,111219.0,111200.0,111416.0,111596.0,111496.0,111641.0,111883.0,112188.0,112411.0,112601.0,112872.0,113392.0,114022.0,114605.0,115065.0,115553.0,116128.0,116623.0,116917.0,117188.0,117382.0,117755.0,117989.0,118364.0,118558.0,118771.0,118916.0,119088.0,119331.0,119438.0,119603.0,119718.0,119995.0,120451.0,121546.0,NaN,124729.0,126049.0,126189.0,127067.0,127414.0,128196.0,128738.0,129328.0,130088.0,130793.0,131511.0,131971.0,132346.0,132419.0,132547.0,132524.0,132422.0,132254.0,132014.0,132173.0,132177.0,132321.0,132127.0,132225.0,132380.0,133032.0,133505.0,134051.0,134400.0,134967.0,135613.0,136102.0,136590.0,136725.0,136530.0,136151.0,136275.0,136707.0,137337.0,137575.0,137931.0,138179.0,138449.0,138636.0,138802.0,138208.0,137512.0,136795.0,136628.0,136228.0,135773.0,135392.0,134770.0,133932.0,133189.0,132247.0,131283.0,130248.0,130095.0,130039.0,130219.0,130392.0,130841.0,131352.0,131430.0,131181.0,130637.0,130546.0,130637.0,130455.0,130296.0,130454.0,130980.0,131366.0,131147.0,130241.0,128782.0,127639.0,126804.0,126407.0,125966.0,125407.0,124819.0,123890.0,123274.0,122771.0,122518.0,122424.0,122361.0,122168.0,121892.0,120903.0,120238.0,119943.0,120246.0,120729.0,120911.0,121210.0,121439.0,121991.0,122476.0,122770.0,122727.0,122968.0,123263.0,124014.0,124929.0,126562.0,128345.0,129986.0,131151.0,132362.0,133688.0,135033.0,136372.0,137593.0,138718.0,139964.0,141302.0,142381.0,143308.0,144178.0,145532.0,146850.0,148466.0,149946.0,151284.0,152468.0,153724.0,155200.0,156514.0,158115.0,159402.0,160644.0,161503.0,161971.0,162318.0,162550.0,163245.0,163767.0,164394.0,165478.0,166518.0,167212.0,167279.0,167752.0,168470.0,169335.0,169585.0,169807.0,170003.0,171100.0,172293.0,172942.0,173418.0,173936.0,174803.0,175355.0,175858.0,175998.0,176105.0,176291.0,176816.0,177493.0,178086.0,178763.0,179315.0,179901.0,180859.0,181862.0,182827.0,183544.0,184466.0,185430.0,186435.0,187384.0,188259.0,189335.0,190241.0,190741.0,190822.0,190969.0,191497.0,192025.0,192652.0,192972.0,193837.0,194401.0,194958.0,194696.0,194963.0,195870.0,197216.0,198080.0,198481.0,198890.0,199804.0,201875.0,204140.0,206623.0,208724.0,210777.0,213157.0,214351.0,216036.0,218153.0,222672.0,227604.0,232956.0,237056.0,240590.0,243006.0,245783.0,248718.0,252080.0,256435.0,261101.0,265558.0,268901.0,271059.0,272400.0,272639.0
3,17426,3,Chicago,city,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,166139.0,166536.0,167368.0,168826.0,170499.0,172008.0,173598.0,175282.0,176928.0,178634.0,180479.0,182259.0,183890.0,185143.0,186789.0,188315.0,190058.0,191482.0,192933.0,194629.0,196416.0,198340.0,199864.0,201093.0,202395.0,203787.0,205605.0,206834.0,208166.0,209016.0,210483.0,212197.0,214267.0,216097.0,217313.0,218765.0,220251.0,222107.0,223677.0,225389.0,226589.0,227809.0,228865.0,230510.0,232266.0,234303.0,236039.0,237862.0,239890.0,241705.0,243394.0,245263.0,247620.0,250097.0,252322.0,254471.0,256412.0,258534.0,260845.0,263400.0,265804.0,268095.0,270328.0,272724.0,275375.0,277971.0,280398.0,282666.0,285374.0,287769.0,290269.0,292733.0,295356.0,297863.0,300221.0,302191.0,303829.0,NaN,305267.0,305664.0,306024.0,305927.0,306047.0,306517.0,307639.0,308738.0,309375.0,309240.0,308595.0,307925.0,306992.0,306281.0,304921.0,303890.0,302715.0,301135.0,300207.0,296063.0,NaN,NaN,293467.0,288495.0,288174.0,283199.0,280695.0,274849.0,271059.0,265306.0,259446.0,255220.0,250583.0,249347.0,246137.0,245064.0,242981.0,241506.0,237514.0,234232.0,230695.0,230395.0,228459.0,228326.0,225504.0,226877.0,225475.0,226811.0,222738.0,220886.0,217038.0,214801.0,211361.0,208225.0,205757.0,203224.0,202110.0,200172.0,199784.0,197983.0,197852.0,196499.0,195393.0,191961.0,190113.0,186620.0,185295.0,181930.0,182673.0,182682.0,183711.0,182998.0,181436.0,180338.0,179230.0,180019.0,180935.0,181766.0,183312.0,184733.0,185970.0,187407.0,189065.0,192164.0,194963.0,197859.0,199540.0,202383.0,203215.0,204818.0,205051.0,207056.0,208148.0,208701.0,209819.0,211624.0,213030.0,213291.0,214040.0,214748.0,215524.0,216288.0,216728.0,217601.0,218417.0,220384.0,221807.0,222303.0,222749.0,223078.0,223321.0,223153.0,223333.0,224649.0,226226.0,229211.0,231164.0,232605.0,232757.0,232923.0,233628.0,234227.0,234846.0,235690.0,237345.0,239254.0,241516.0,243706.0,246315.0,247918.0,248736.0,248387.0,248272.0,248462.0,249600.0,250080.0,250728.0,252046.0,254397.0,256564.0,256995.0,257112.0,257174.0,257461.0,257467.0,257258.0,257917.0,258549.0,259637.0,260447.0,260559.0,261069.0,261214.0,261813.0,261519.0,261110.0,260676.0,260236.0,259915.0,259593.0,259510.0,259625.0,260161.0,261128.0,261799.0,262116.0,262013.0,262362.0,264051.0,266204.0,270202.0,273716.0,276541.0,278154.0,278668.0,280878.0,282423.0,285237.0,286248.0,288347.0,290773.0,293804.0,295841.0,297856.0,300413.0,302821.0,305104.0,306404.0,308303.0,309649.0,312487.0,314663.0,315910.0,315587.0,315429.0

### Melt the data to long-form and prepare it for time series analysis

In [4]:
id_cols = ['RegionID', 'SizeRank', 'RegionName', 'RegionType', 'StateName', 'State', 'Metro', 'CountyName']
melted = pd.melt(df_largest, id_vars = id_cols, value_name = 'House Value', var_name = 'Month')
melted

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,Month,House Value
0,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,2000-01-31,253690.0
1,12447,1,Los Angeles,city,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,2000-01-31,234181.0
2,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,2000-01-31,109068.0
3,17426,3,Chicago,city,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,2000-01-31,166139.0
4,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,2000-02-29,255517.0
...,...,...,...,...,...,...,...,...,...,...
1087,17426,3,Chicago,city,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,2022-08-31,315587.0
1088,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,2022-09-30,781622.0
1089,12447,1,Los Angeles,city,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,2022-09-30,966595.0
1090,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,2022-09-30,272639.0
1091,17426,3,Chicago,city,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,2022-09-30,315429.0

### Convert the melted dates into datetime datatype

In [5]:
melted['Month'] = pd.to_datetime(melted['Month'])
melted.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1092 entries, 0 to 1091
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   RegionID     1092 non-null   int64
 1   SizeRank     1092 non-null   int64
 2   RegionName   1092 non-null   object
 3   RegionType   1092 non-null   object
 4   StateName    1092 non-null   object
 5   State        1092 non-null   object
 6   Metro        1092 non-null   object
 7   CountyName   1092 non-null   object
 8   Month        1092 non-null   datetime64[ns]
 9   House Value  1087 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 85.4+ KB

### Make the datetime column the index

In [6]:
melted = melted.set_index('Month')
melted.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,Metro,CountyName,House Value
Month,,,,,,,,,
2000-01-31,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,253690.0
2000-01-31,12447,1,Los Angeles,city,CA,CA,"Los Angeles-Long Beach-Anaheim, CA",Los Angeles County,234181.0
2000-01-31,39051,2,Houston,city,TX,TX,"Houston-The Woodlands-Sugar Land, TX",Harris County,109068.0
2000-01-31,17426,3,Chicago,city,IL,IL,"Chicago-Naperville-Elgin, IL-IN-WI",Cook County,166139.0
2000-02-29,6181,0,New York,city,NY,NY,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,255517.0

### Resample the dataframe as monthly frequency, grouped by City

In [7]:
df_ts = melted.groupby('RegionName').resample("M").mean()
df_ts

/var/folders/_5/txdkxz9d07zcw7bs_mc8cnmr0000gn/T/ipykernel_1636/906173531.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_ts = melted.groupby('RegionName').resample("M").mean()
/var/folders/_5/txdkxz9d07zcw7bs_mc8cnmr0000gn/T/ipykernel_1636/906173531.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_ts = melted.groupby('RegionName').resample("M").mean()
/var/folders/_5/txdkxz9d07zcw7bs_mc8cnmr0000gn/T/ipykernel_1636/906173531.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_ts = melted.groupby('RegionName').resample("M").mean()
/var/folders/_5/txdkxz9d07zcw7bs_mc8cnmr0000gn/T/ipykernel_1636/906173531.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_ts = melted.groupby('RegionName').resample("M").mean()

                       RegionID  SizeRank  House Value
RegionName Month
Chicago    2000-01-31   17426.0       3.0     166139.0
           2000-02-29   17426.0       3.0     166536.0
           2000-03-31   17426.0       3.0     167368.0
           2000-04-30   17426.0       3.0     168826.0
           2000-05-31   17426.0       3.0     170499.0
...                         ...       ...          ...
New York   2022-05-31    6181.0       0.0     768797.0
           2022-06-30    6181.0       0.0     773944.0
           2022-07-31    6181.0       0.0     777692.0
           2022-08-31    6181.0       0.0     779960.0
           2022-09-30    6181.0       0.0     781622.0

[1092 rows x 3 columns]